### ISSUE TITLE
'extract_url' function error

### ISSUE THREAD

**Issue by UIlynn** [sdushantha/facebook-dl#4]
When tried with url it gives the following error:

```
Traceback (most recent call last):
  File "02 facebook_dl.py", line 65, in <module>
    main()
  File "02 facebook_dl.py", line 51, in main
    file_url = extract_url(r.text, args.resolution)
  File "02 facebook_dl.py", line 25, in extract_url
    url = re.search('sd_src:"(.+?)"', html)[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sdushantha** [comment]
I think Facebook has changed something which means I need to find where the new url is located. I will fix this soon :)

**Comment by OrganicChem** [comment]
Any update on this?

**Comment by sdushantha** [comment]
@OrganicChem Im really sorry, I havent had much time to work on this, really busy with school at the moment.

**Comment by sdushantha** [comment]
@OrganicChem @UIlynn  It seems to be working now. I just tried downloading a video and it worked. Could you test again?

**Comment by sdushantha** [comment]
Seems to work just fine for me:
![out](https://user-images.githubusercontent.com/27065646/79065713-ba4f3f00-7cb2-11ea-9c08-61842fcc6791.gif)

**Comment by onoakino** [comment]
I'm still getting an error though.

muning-MacBook-Pro:facebook-dl muning$ python3 facebook-dl.py https://www.facebook.com/irwansamsuri.pg/videos/10216440231261658/
✔ Fetched source code
Traceback (most recent call last):
  File "facebook-dl.py", line 64, in <module>
    main()
  File "facebook-dl.py", line 49, in main
    file_url = extract_url(request.text, args.resolution)
  File "facebook-dl.py", line 28, in extract_url
    url = re.findall('hd_src:"(.+?)"', html)[0]

**Comment by sdushantha** [comment]
@onoakino This tool only downloads videos from public groups at the moment. We would have to add way of logging into Facebook to download private posts, and I havent really figured out how to do that yet.
